# Generated by Django 3.2.2 on 2021-05-07 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('part_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='部品ID')),
                ('part_name', models.CharField(blank=True, default=1, max_length=40, null=True, verbose_name='部品名')),
            ],
            options={
                'verbose_name': '部品',
                'verbose_name_plural': '部品一覧',
            },
        ),
    ]
