# Generated by Django 3.2.2 on 2021-05-07 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test00',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='PartID')),
                ('part_name', models.CharField(blank=True, default=1, max_length=40, null=True, verbose_name='PartName')),
            ],
            options={
                'verbose_name': 'Part',
            },
        ),
        migrations.CreateModel(
            name='Test01',
            fields=[
                ('part_id', models.CharField(default='001', max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='PartID')),
                ('part_name', models.CharField(blank=True, default=1, max_length=40, null=True, verbose_name='PartName')),
            ],
            options={
                'verbose_name': 'Test01',
            },
        ),
        migrations.CreateModel(
            name='Test02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(default='001', max_length=40, unique=True, verbose_name='PartID')),
                ('part_name', models.CharField(blank=True, default=1, max_length=40, null=True, verbose_name='PartName')),
            ],
            options={
                'verbose_name': 'Test02',
            },
        ),
        migrations.AlterModelOptions(
            name='parts',
            options={'verbose_name': 'Part', 'verbose_name_plural': 'Parts'},
        ),
        migrations.AlterField(
            model_name='parts',
            name='part_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='PartID'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='part_name',
            field=models.CharField(blank=True, default=1, max_length=40, null=True, verbose_name='PartName'),
        ),
    ]
